name: todo
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  logger: ^1.0.0
  uuid: ^4.4.0
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  sqflite: ^2.3.3+1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5


  # flutter_gen: any
  intl: any
  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_launcher_icons:
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  android: true
  ios: true
  min_sdk_android: 16
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
